name: CD ( test docker )

on:
  pull_request:
    branches:
      - main 
      
permissions:
  contents: write
  pull-requests: write
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Install Dependencies
        run: |
            docker exec inventaire sh -c "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
            docker exec inventaire composer install -n
        
      - name: Update Dependencies
        run:  docker exec inventaire composer update

      - name: Simulate Navigation ( test url docker ) 
        run: |
          curl --fail http://localhost:8888/ || exit 1

      - name: Stop Docker Compose
        if: always()
        run: docker-compose down

