name: PHPUnit Tests

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start docker
      run: docker compose up -d

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Dependencies
      run: |
        composer install --prefer-dist --no-interaction --no-progress

    - name: Update Dependencies
      run: composer update

    - name: Test api
      run: phpunit .\ApiIntegrationTest.php
    
    - name: Stop docker
      if: always()
      run: docker-compose down
